### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by ofWorse** [ofWorse/Graphika#114]
Пишите сюда идеи касательно оптимизации кодовой базы.
Особое внимание стоит уделить таким пунктам как leftwidget, rightwidget, mainwindow и toolbar.
![image](https://github.com/ofWorse/Graphika/assets/91342177/86b413c1-ae19-4189-a9d5-77dbe953e341)

**Comment by Vovanimuss** [comment]
Касательно leftwidget:
Ультимативным решением я бы назвал переписывание кодовой базы по ООП заветам, где у нас есть супер класс widget, с базовым необходимым функционалом, таким как переназначение bool полей и тд + фабричный метод, который способен порождать экземпляры виджетов, в зависимости от того, из кого места пришёл сигнал, уже с добавочным функционалом(например, другой лейаут с таблицей под уравнения). Но это конечно монструозное кол-во работы на данный момент.
Если сбавить обороты и скорее просто избавиться от повторяемого кода: 
Объединить данный код в общий метод, в кач-ве аргументов которого **всегда** принимаются все переменные поля + вызываются остальные служебные методы, что-то вроде:
void onCreatingNewWidget(equationState::bool, buffer::buffer, hideFirstLayerState::bool){
    equationOpened = equationState;
    hideAll();
    deleteAll();
    initLabels();
    connectLabels( buffer );
    setRange();
    initLayout();
    hideFirstLayer( hideFirstLayerState );
}
+ предложение вынести служебные методы (e.x. initLabels) в отдельный подключаемый пакет, чтобы чуток разнести логику работы приложения на нашей стороне с логикой самого QT (опционально)
![image](https://github.com/ofWorse/Graphika/assets/110857680/2008c59c-55d6-4b15-b52b-5d260a379fc4)

**Comment by ofWorse** [comment]
Я думаю сделать фабрику чтобы инициализация виджета была более инкапсулированной, но еще там есть много заглушек  в виде булевых переменных, от которых тоже следует избавиться. Хранить состояние виджета я бы предпочел при помощи enum. 
Например : enum class WidgetState { FUNCTION, DERIVATION, INTEGRATION, ... }.
Из типичных упрощений пока что видится именно такой вариант.

**Comment by ofWorse** [comment]
Есть такой участок. Его точно нужно перенести в другой файл: // TODO: Переместить реализацию в MathUtils
    if( !nodes->isVisible() && manualInput == false )
    {
        for( double i = min; i <= max; i += step )
        {
            X.push_back( i );
        }
        parser->setDataX( X );
        Y = parser->parseExpression( expression.toStdString().c_str() );
    }
    else if( nodes->isVisible() && manualInput == false )
    {
        setupNodes( nodes->value() );
        parser->setDataX( X );
        Y = parser->parseExpression( expression.toStdString().c_str() );
    }
    // TODO: deprecated методы. Заменить логику на более новую.
    else if( manualInput )
    {
        X = fillDataFromTable( 0 );
        Y = fillDataFromTable( 1 );
    }

**Comment by ofWorse** [comment]
И вот о чем я говорю. Не только здесь используются булевые операторы, которые в перспективе могут разрастись, от чего поддерживать программу будет сложнее. Предлагаю сделать некоторого рода схему взаимодействия классов для генерации виджетом левой части.
void LeftWidget::rebuildWidgets( pymodules::Modules modules, SpecialBuffer& buffer )
{
    switch( modules )
    {
    case pymodules::Modules::DIFFERENTIATION:
        derivativeLabelActive = true;
        polynomialsLabelsActive = false;
        buildWidgetForDerivativeOperations( buffer );
        break;
    case pymodules::Modules::INTEGRATION:
        derivativeLabelActive = false;
        polynomialsLabelsActive = false;
        buildWidgetForIntegrationOperations( buffer );
        break;
    case pymodules::Modules::EQUATIONS:
        derivativeLabelActive = false;
        polynomialsLabelsActive = false;
        buildWidgetForEquationOperations( buffer );
        break;
    case pymodules::Modules::NIL:
        derivativeLabelActive = false;
        polynomialsLabelsActive = false;
        setWidgetToDefaultStatement( buffer );
        break;
    case pymodules::Modules::POLYNOMIALS:
        derivativeLabelActive = false;
        polynomialsLabelsActive = true;
        setWidgetToDefaultStatement( buffer );
        break;
    };
}

**Comment by ofWorse** [comment]
![ex](https://github.com/ofWorse/Graphika/assets/91342177/9b4001b7-5a30-475d-9213-d82b7b3e73ca)

**Comment by ofWorse** [comment]
В принципе да, можно представить такую реализацию по принципу единой ответственности.
Слоты и сигналы скорее всего останутся, но у нас будет общий метод генерации виджета в зависимости от смены состояния. Генерация будет уже от соответствующего класса.
Я тут настрочил.
class LeftWidget : public QWidget
{
    Q_OBJECT

public:
    LeftWidget( SpecialBuffer& buffer, QWidget* parent = nullptr );

private:
    ExpressionInputWidget* expressionInput;
    VariableInputWidget* variableInput;
    TableWidget* dataTable;
    EquationWidget* equationWidget;
    ResultWidget* resultWidget;
    ControlButtonsWidget* controlButtons;

    QVBoxLayout* mainLayout;

    void setupWidgets();
    void connectSignals(); 
....
}

**Comment by ofWorse** [comment]
Тогда билдер не нужен получается.

**Comment by ofWorse** [comment]
хоя я так посмотрел. Мне больше приглянулся паттерн "стратегия".
Суть заключается в том что у нас есть класс стратегия, которого наследуют каждый из модулей. Они должны уметь сохранять состояние объектов или наоборот сбрасывать состояние. а класс LeftWidget будет формировать новую стратегию, а конкретно ту, что будет ей передана в качестве макроса.

**Comment by ofWorse** [comment]
в общем, я разобрался с тем что здесь паттерны не нужны. Только принцип единой ответственности.
