### ISSUE TITLE
numerical differentiation #0024

### ISSUE THREAD

**Issue by ofWorse** [ofWorse/Graphika#30]
Добавить модуль с алгоритмами численного дифференцирования.
На выходе ожидаются табличные значения по f'(x).

**Comment by Vovanimuss** [comment]
Прошу конкретизировать ожидаемый вид параметров ввода/вывода требуемого модуля.

**Comment by ofWorse** [comment]
Подумал над решением. Так как численное дифференцирование по двух/трех/пяти точечной схеме требует в наличии самой функции f(x), можно поступить следующим образом.
После того как в программе пользователь нашел все точки для f(x), он ищет точки для f'(x). Для этого твоему методу численного дифференцирования нужно будет иметь помимо точек f(x) еще и строковую функцию с некоторым шагом. Шаг я думаю может генерировать твоя программа. На выходе ожидаются точки f'(x) для каждого x.
По поводу подбора шага под конкретную функцию: думаю можно будет обойтись обычным сравнением нескольких результатов. Если разница между вычислениями 0.01, то в принципе решение можно считать успешным и можно возвращать массив f'(x).

Подытожив.
На вход: точки X и Y, строковая функция.
На выходе: точки f'(x).

Есть подозрения что этот метод будет слишком нагруженным. Надо будет протестировать, ну или может быть у тебя есть более легкий способ решения).

**Comment by ofWorse** [comment]
Либо можно сделать по другому. По сути метод выше требует парсинга строки на питоне. Если это ресурсоемкая операция, то лучше обойтись без нее. Вместо этого твой метод может сразу брать минимальный шаг для более точных вычислений и строить формулу для каждой точки x. Например: для точки x = 1, левосторонняя двухточечная формула выглядит так: f'(1) = ( f(1) - f(1 - h) ) / h. Только вместо f - строковая функция, переданная в твой метод.
Получается твоя программа подставляет точки по x для каждого f'(x) и возвращает список строк ( список формул для каждой точки x ). После этого мой stringparser считает эти точки.
