### ISSUE TITLE
integration #0029

### ISSUE THREAD

**Issue by ofWorse** [ofWorse/Graphika#56]
Добавить метод, который принимает строковую функцию и массив точек по x для расчета первообразной функции для каждой из заданных точек. На выходе ожидается массив точек y.

**Comment by Vovanimuss** [comment]
После анализа задания было вынесено решение, что реализация данного метода невозможна:

Первообразная функции имеет: F(x) = antidiviretive(f(x)) + C,  где C - любая константа. С помощью численных методов невозможно сконструировать F(x) в её первоначальном виде.

**Comment by ofWorse** [comment]
Хорошо. Тогда на данный момент задачу закрываем.
